/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.HeadlessException;
import konfigurasi.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.text.*;

/**
 *
 * @author home
 */
public class Keluar extends javax.swing.JFrame {
 Connection cnn;
    Statement stm;
    ResultSet rss;
    DefaultTableModel isi;
    Object[] title= {"No Tiket","No Pol","Jenis","Tgl Masuk","Jam Masuk","Tgl Keluar","Jam Keluar"};
    
    public void buka_database(){
        try{
            Koneksi konek = new Koneksi("parkir_db");
            cnn=konek.aktifkan_koneksi();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Coba Lagi, Koneksi Gagal"); 
        }
    }
    final void tampil_parkir(){
        isi=new DefaultTableModel(null,title);
        try{
            stm=cnn.createStatement();
            String perintah="SELECT * from parkir order by no_tiket desc";
            rss=stm.executeQuery(perintah);
            while(rss.next()){
                String vnotik =rss.getString("no_tiket");
                String vnopol =rss.getString("nopol");
                String vjenis =rss.getString("jenis");
                String vtgl_msk =rss.getString("tgl_masuk");
                String vjam_msk =rss.getString("jam_masuk");
                String vtgl_klr =rss.getString("tgl_keluar");
                String vjam_klr =rss.getString("jam_keluar");

                String[] data ={vnotik,vnopol,vjenis,vtgl_msk,vjam_msk,vtgl_klr,vjam_klr};
                isi.addRow(data);
            }

        }catch(Exception e){
            System.out.println("gagal Mengambil barang :  "+e);
            System.exit(0);
        }
        tabel_parkir.setModel(isi);
    }
    
    final void dapatkan_data(){
        isi=new DefaultTableModel(null,title);
        try{
            stm=cnn.createStatement();
            String perintah="SELECT  tgl_keluar, jam_keluar, TIME_FORMAT(`jam_keluar`,'%H')-TIME_FORMAT(`jam_masuk`,'%H') AS durasi FROM parkir where nopol='"+cari.getText()+"';";
            rss=stm.executeQuery(perintah);
            while(rss.next()){
                kkeluar_tgl.setText(rss.getString("tgl_keluar"));
                kkeluar_jam.setText(rss.getString("jam_keluar"));
                durasi.setText(rss.getString("durasi"));
            }

        }catch(Exception e){
            System.out.println("gagal Mengambil dapat data :  "+e);
            System.exit(0);
        }
        tabel_parkir.setModel(isi);
    }
    
    public void cari_data(){
        isi=new DefaultTableModel(null,title);
        try{
           stm=cnn.createStatement();
           String perintah="select * from parkir where nopol like '%"+cari.getText()+"%'";
           rss=stm.executeQuery(perintah);
           while(rss.next()){
                String vnotik =rss.getString("no_tiket");
                String vnopol =rss.getString("nopol");
                String vjenis =rss.getString("jenis");
                String vtgl_msk =rss.getString("tgl_masuk");
                String vjam_msk =rss.getString("jam_masuk");
                String vtgl_klr =rss.getString("tgl_keluar");
                String vjam_klr =rss.getString("jam_keluar");

                String[] data ={vnotik,vnopol,vjenis,vtgl_msk,vjam_msk,vtgl_klr,vjam_klr};
                isi.addRow(data);
           }
        }catch(Exception e){
           System.out.println("gagal Mengambil barang :  "+e);
           System.exit(0);
       }
       tabel_parkir.setModel(isi);
    }
    public void akumulasi_biaya(){
        int vdurasi;
        double vbj, vbiaya;
        
        vdurasi=Integer.parseInt(durasi.getText());
        vbj=Double.parseDouble(kbj.getText());
        
        if(vdurasi<=1){
            vbiaya=vbj;
        }else{
            vbiaya=(vbj)+((vdurasi-1)*2000);
        }
        biaya.setText(""+vbiaya);
    }
    
    public void bersih(){
        cari.setText("");
        kjenis.setText("");
        kbj.setText("");
        kkeluar_jam.setText("");
        kkeluar_tgl.setText("");
        kmasuk_jam.setText("");
        kmasuk_tgl.setText("");
        biaya.setText("");
        durasi.setText("");
        
    }
    /**
     * Creates new form Keluar
     */
    public Keluar() {
        initComponents();
        tengah tengah = new tengah(this);
        buka_database();
        tampil_parkir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kjenis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kmasuk_tgl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kmasuk_jam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kbj = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kkeluar_tgl = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kkeluar_jam = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        durasi = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        biaya = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_parkir = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Logout1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parkir Keluar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sistem Parkir Sederhana");

        jLabel4.setText("Cari Nopol");

        cari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cariKeyTyped(evt);
            }
        });

        jLabel5.setText("Jenis");

        kjenis.setEditable(false);
        kjenis.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                kjenisInputMethodTextChanged(evt);
            }
        });
        kjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kjenisActionPerformed(evt);
            }
        });
        kjenis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kjenisKeyReleased(evt);
            }
        });

        jLabel6.setText("Masuk tgl :");

        kmasuk_tgl.setEditable(false);
        kmasuk_tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kmasuk_tglKeyReleased(evt);
            }
        });

        jLabel7.setText("Jam :");

        kmasuk_jam.setEditable(false);
        kmasuk_jam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kmasuk_jamKeyReleased(evt);
            }
        });

        jLabel10.setText("/Jam  :");

        kbj.setEditable(false);
        kbj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbjActionPerformed(evt);
            }
        });
        kbj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kbjKeyReleased(evt);
            }
        });

        jLabel8.setText("Keluar tgl :");

        kkeluar_tgl.setEditable(false);
        kkeluar_tgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kkeluar_tglKeyReleased(evt);
            }
        });

        jLabel9.setText("Jam :");

        kkeluar_jam.setEditable(false);
        kkeluar_jam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kkeluar_jamKeyReleased(evt);
            }
        });

        jLabel11.setText("Durasi : ");

        durasi.setEditable(false);
        durasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                durasiKeyReleased(evt);
            }
        });

        keluar.setText("Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        keluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keluarKeyReleased(evt);
            }
        });

        jLabel12.setText("Biaya:");

        biaya.setEditable(false);
        biaya.setBackground(new java.awt.Color(255, 255, 153));
        biaya.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        biaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                biayaKeyReleased(evt);
            }
        });

        tabel_parkir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_parkir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_parkirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_parkir);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Parkir Keluar");

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Logout1.setText("Login");
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(kmasuk_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(kmasuk_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(21, 21, 21)
                                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(kkeluar_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kkeluar_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durasi)
                                    .addComponent(kbj)
                                    .addComponent(kjenis, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel12)
                                .addGap(47, 47, 47)
                                .addComponent(biaya))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jLabel2)))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Logout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Logout1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Logout))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(kjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kbj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(kmasuk_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kmasuk_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kkeluar_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kkeluar_jam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(biaya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        cari_data();
    }//GEN-LAST:event_cariKeyReleased

    private void kjenisInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kjenisInputMethodTextChanged

    }//GEN-LAST:event_kjenisInputMethodTextChanged

    private void kjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kjenisActionPerformed

    private void kjenisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kjenisKeyReleased

    }//GEN-LAST:event_kjenisKeyReleased

    private void kmasuk_tglKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kmasuk_tglKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_kmasuk_tglKeyReleased

    private void kmasuk_jamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kmasuk_jamKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_kmasuk_jamKeyReleased

    private void kbjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbjActionPerformed

    private void kbjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kbjKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_kbjKeyReleased

    private void kkeluar_tglKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kkeluar_tglKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_kkeluar_tglKeyReleased

    private void kkeluar_jamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kkeluar_jamKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_kkeluar_jamKeyReleased

    private void durasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durasiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_durasiKeyReleased

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        if( !"".equals(cari.getText())){
            try{
                stm=cnn.createStatement();
                String perintah="update parkir set tgl_keluar=curdate(), jam_keluar=curtime() where nopol='"+cari.getText()+"'";
                stm.executeUpdate(perintah);
                JOptionPane.showMessageDialog(null,"Berhasil Update Keluar");
                nopol.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data Gagal Diupdate");
                System.out.println("erornya : "+e);
            }
            dapatkan_data();
            akumulasi_biaya();
            tampil_parkir();
        }else{
            JOptionPane.showMessageDialog(null, "Anda Belum Input Nopol");
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void biayaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_biayaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_biayaKeyReleased

    private void tabel_parkirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_parkirMouseClicked
        bersih();
        cari.setText(tabel_parkir.getValueAt(tabel_parkir.getSelectedRow(),1).toString());
        kjenis.setText(tabel_parkir.getValueAt(tabel_parkir.getSelectedRow(),2).toString());
        kmasuk_tgl.setText(tabel_parkir.getValueAt(tabel_parkir.getSelectedRow(),3).toString());
        kmasuk_jam.setText(tabel_parkir.getValueAt(tabel_parkir.getSelectedRow(),4).toString());

        try{
            stm=cnn.createStatement();
            String perintah="SELECT tarif from kendaraan where jenis='"+kjenis.getText()+"'";
            rss=stm.executeQuery(perintah);
            while(rss.next()){
                kbj.setText(rss.getString("tarif"));
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null ,"Gagal  ");
            System.out.println("Erornya :  "+e);
            System.exit(0);
        }
    }//GEN-LAST:event_tabel_parkirMouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Apakah Semua kendaraan sudah diinput?","Keluar",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        // TODO add your handling code here:
        cari_data();
    }//GEN-LAST:event_keluarMouseClicked

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
        // TODO add your handling code here:
         {
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_Logout1ActionPerformed

    private void cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyTyped
        // TODO add your handling code here:
        cari_data();
        
    }//GEN-LAST:event_cariKeyTyped

    private void keluarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keluarKeyReleased
        // TODO add your handling code here:
        cari_data();
    }//GEN-LAST:event_keluarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton Logout1;
    private javax.swing.JTextField biaya;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField durasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kbj;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kjenis;
    private javax.swing.JTextField kkeluar_jam;
    private javax.swing.JTextField kkeluar_tgl;
    private javax.swing.JTextField kmasuk_jam;
    private javax.swing.JTextField kmasuk_tgl;
    private javax.swing.JTable tabel_parkir;
    // End of variables declaration//GEN-END:variables
}
